name: Actualizar lista de issues en README

on:
  push:
    branches: [ main ]

jobs:
  actualizar_readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Obtener Lista de issues abiertos
        id: obtener_lista_issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issues = await github.paginate(github.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
              state: 'open'
            });

            const issueList = issues.map(issue => `* [${issue.title}](${issue.html_url})`).join('\n');

            return {
              issues: issueList
            };

      - name: Actualizar Readme
        run: |
          issue_list="${{ steps.obtener_lista_issues.outputs.issues }}"
          # Usamos sed para reemplazar la sección de Issues Abiertas en el README.md
          sed -i '/## Issues Abiertas/,$d' README.md
          echo -e "## Issues Abiertas\n\n$issue_list\n" >> README.md

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m 'Actualizar lista de issues en README'
          git push
