name: Actualizar lista de issues en README

on:
  push:
    branches: [ main ]

jobs:
  actualizar_readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Obtener Lista de issues abiertos
        id: obtener_lista_issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issues = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
              state: 'open'
            });

            const issueList = issues.data.map(issue => `* [${issue.title}](${issue.html_url})`).join('\n');

            return issueList;

      - name: Actualizar Readme
        uses: actions/replace-text@v2
        with:
          file: README.md
          regex: '## Issues Abiertas.*'
          replacement: |
            ## Issues Abiertas

            ${{ steps.obtener_lista_issues.outputs.result }}
